---
  - name: add dhcp_server mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_add }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'add'

  - name: remove dhcp_server mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'remove'

  - name: enable dhcp_server mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable dhcp_server mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: set dhcp_server mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'


  - name: add dhcp_server cisco
    routeros_command:
      commands: "{{ cisco_dhcp_server_add }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'add'

  - name: remove dhcp_server cisco
    routeros_command:
      commands: "{{ cisco_dhcp_server_remove }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'remove'

  - name: enable dhcp_server cisco
    routeros_command:
      commands: "{{ cisco_dhcp_server_enable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'enable'

  - name: disable dhcp_server cisco
    routeros_command:
      commands: "{{ cisco_dhcp_server_disable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'disable'

  - name: set dhcp_server cisco
    routeros_command:
      commands: "{{ cisco_dhcp_server_set }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
