---

  - name: set ntp client mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

  # FIXME: В документации не просят делать config: {{...}}
  - name: set ntp client cisco
    cisco.ios.ios_ntp: "{{ cisco_config }}"
    state: present
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
