---
mikrotik_config_add: /user add name={{ username }} password={{ password }} group={{ group }}
mikrotik_config_remove: /user remove {{ username }}
mikrotik_config_enable: /user enable {{ username }}
mikrotik_config_disable: /user disable {{ username }}
mikrotik_config_set: /user set {{ username }} password={{ password }} group={{ group }}

cisco_config_add:
  - name: "{{ username }}"
    configured_password: "{{ password }}"
    privilege: "{{ privilege }}"
    state: present

cisco_config_remove:
  - name: "{{ username }}"
    state: absent

#TODO: ???

cisco_config_enable:
  - name: "{{ username }}"
    state: present

cisco_config_disable:
  - name: "{{ username }}"
    state: absent

cisco_config_set:
  - name: "{{ username }}"
    configured_password: "{{ password }}"
    privilege: "{{ privilege }}"
    state: present
