---
mikrotik_config_add: /user add name={{ username }} password={{ password }} group={{ group }}
mikrotik_config_remove: /user remove {{ username }}
mikrotik_config_enable: /user enable {{ username }}
mikrotik_config_disable: /user disable {{ username }}
mikrotik_config_set: /user set {{ username }} password={{ password }} group={{ group }}
cisco_config: /system identity set name={{ local_hostname }}
