---
mikrotik_config_add: /user add name={{ name }} password={{ password }} group={{ group }}
mikrotik_config_remove: /user remove name={{ name }}
mikrotik_config_enable: /user enable name={{ name }}
mikrotik_config_disable: /user disable name={{ name }}
mikrotik_config_set: /user set name={{ name }} password={{ password }} group={{ group }}
cisco_config: /system identity set name={{ local_hostname }}
