stages: 
    - test
    - deploy

test_deploy:
  stage: test
  before_script:
    - sudo apt install yamllint --yes
  script: 
  - cd /home/ifilyanin/Desktop/multivendor_module_ansible
  - git pull https://adeptvin1:Adeptvin3@gitlab.com/adeptvin1/multivendor_module_ansible.git
  tags:
  - ansible_test

test_play:
  stage: test
  script: 
  - ansible-playbook $CI_COMMIT_TITLE
  - yamllint *_playbook.yml && echo "OK"
  rules:
  - if: '$CI_COMMIT_TITLE != ".gitlab-ci.yml"'
  tags:
  - ansible_test
 
second:
  stage: deploy
  script: 
  - echo $CI_COMMIT_REF_SLUG
  tags:
  - ansible_test