stages: 
    - test
    - deploy

first:
  stage: test
  script: 
  - cd /home/ifilyanin/Desktop/multivendor_module_ansible
  - git pull --adeptvin1 --Adeptvin3
  tags:
  - ansible_test
 
second:
  stage: deploy
  script: 
  - ansible --version
  tags:
  - ansible_test