- name: "change_hostname"
  hosts: "{{ select_hosts }}"
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_user
        username: "{{ username }}"
        password: "{{ password }}"
        group: "{{ group }}"
        action: "{{ action }}"
