- name: "change_hostname"
  hosts: "{{ hosts }}"
  gather_facts: false
  ignore_errors: true
  tasks:

    - name: show interface
      routeros_facts:
        gather_subset: "{{ subset }}"
      register: substes_register

    - name: collect_facts
      setup:
        fact_path: /facts.yml


    # - copy: content="{{ substes_register | to_yaml }}" dest=/home/stark/Desktop/test.yml
