- name: config capsman
  hosts: SW01.L3.01.LAB
  gather_facts: no
  ignore_errors: true
  roles:
      - role: config_capsman
        cap_interface: corp
        mtu: 1600
        arp: disabled
        submenu: cap_interface
        action: add

      - role: config_capsman
        numbers_cap_interface: 0
        submenu: cap_interface
        action: disable

      - role: config_capsman
        numbers_cap_interface: 0
        submenu: cap_interface
        action: enable

      - role: config_capsman
        cap_interface: corp2
        mtu: 1500
        arp: enabled
        submenu: cap_interface
        action: set

      
