- name: config mpls
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_mpls
        numbers_ldp_neighbor: 0
        transport: 1.1.1.1
        send_targeted: no
        submenu: ldp_neighbor
        action: add
