- name: "change_hostname"
  hosts: AP01.L3.01.TYRMA
  gather_facts: true
  ignore_errors: true
  tasks:

    - name: show interface
      routeros_facts:
        gather_subset: all
      register: config_mikrotik

    - name: Debug config
      debug: var=ansible_net_model
