- name: "change_hostname"
  hosts: 10.100.0.3
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_user
        username: test_user
        password: test_user
        privilege: 15
        action: add
