- name: "change_hostname"
  hosts: 10.10.50.11
  gather_facts: true
  ignore_errors: true
  tasks:

    - name: show interface
      routeros_facts:
        gather_subset: default

    - name: Debug config
      debug: var=ansible_net_model
