- name: "change_hostname"
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_interface_ethernet
        interface: ether3
        action: enable
      - role: config_interface_ethernet
        interface: ether3
        action: disable
      - role: config_interface_ethernet
        interface: ether3
        action: auto_negotiation
        state: no
      - role: config_interface_ethernet
        interface: ether3
        action: auto_negotiation
        state: yes
      - role: config_interface_ethernet
        interface: ether3
        action: speed
        speed: 100Mbps
