- name: "change_hostname"
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_ip_route
        address: 5.5.5.5/32
        gateway: wlan1
        action: add

      # - role: config_ip_route
      #   numbers_route: 1
      #   action: disable
      #
      # - role: config_ip_route
      #   numbers_route: 1
      #   action: enable
      #
      # - role: config_ip_route
      #   numbers_route: 1
      #   address: 5.5.5.5/32
      #   gateway: wlan1
      #   check_gateway: ping
      #   action: set
      #
      # - role: config_ip_route
      #   numbers_route: 1
      #   action: remove
