- name: config mpls
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:

      - role: config_mpls
        range: 16-1048574
        propagate_ttl: 'no'
        submenu: mpls_settings
        action: set
