- name: "change_hostname"
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_interface_wireless
        wireless_interface: test_wlan
        ssid: TEST_SSID
        mode: ap-bridge
        security_profile: Profile_TEST
        hide_ssid: 'no' #все no , yes в скобочках!
        submenu: interface
        action: set

      - role: config_interface_wireless
        wireless_interface: test_wlan
        submenu: interface
        action: disable

      - role: config_interface_wireless
        wireless_interface: test_wlan
        submenu: interface
        action: enable

      - role: config_interface_wireless
        security_profile: Profile_TEST
        password: rer
        mode: dynamic-keys
        submenu: profile
        action: add

      - role: config_interface_wireless
        security_profile: Profile_TEST
        rename_security_profile: Profile_TEST1
        password: rer
        mode: dynamic-keys
        submenu: profile
        action: set

      - role: config_interface_wireless
        security_profile: Profile_TEST1
        submenu: profile
        action: remove
