- name: "change_hostname"
  hosts: BRAS
  gather_facts: true
  ignore_errors: true
  tasks:

    - name: show interface
      routeros_facts:
        gather_subset: config
      register: config_mikrotik

    - name: Debug config
      debug: var=config_mikrotik
