- name: "change_hostname"
  hosts: router_cisco
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_interface_ethernet
        interface: FastEthernet 2/0
        action: enable
      - role: config_interface_ethernet
        interface: FastEthernet 2/0
        action: disable
