- name: "change_hostname"
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_ip_route
        address: 1.1.1.1/32
        gateway: 192.168.88.1
        check_gateway: ping
        distance: 10
        action: add

      - role: config_ip_route
        numbers_route: 1
        action: disable
      - role: config_ip_route
        numbers_route: 1
        action: enable

      - role: config_ip_route
        numbers_route: 1
        address: 1.1.1.2/32
        gateway: 192.168.88.1
        check_gateway: ping
        distance: 100
        action: set

      - role: config_ip_route
        numbers_route: 1
        action: remove
