- name: config capsman
  hosts: SW01.L3.01.LAB
  gather_facts: no
  ignore_errors: true
  roles:
      - role: config_capsman
        cap_interface: corp
        mtu: 1600
        arp: disabled
        submenu: cap_interface
        action: add

      - role: config_capsman
        numbers_cap_interface: 0
        submenu: cap_interface
        action: disable

      - role: config_capsman
        numbers_cap_interface: 0
        submenu: cap_interface
        action: enable

      - role: config_capsman
        numbers_cap_interface: 0
        cap_interface: corp2
        mtu: 1500
        arp: enabled
        submenu: cap_interface
        action: set

      - role: config_capsman
        numbers_cap_interface: 0
        submenu: cap_interface
        action: remove


      - role: config_capsman
        radio_mac: 21:00:7D:84:9D:2F
        action: create_disabled
        name_format: identity
        cfg_name: cfg_1
        submenu: caps_provisioning
        action: add

      - role: config_capsman
        numbers_caps_provisioning: 0
        submenu: caps_provisioning
        action: disable

      - role: config_capsman
        numbers_caps_provisioning: 0
        submenu: caps_provisioning
        action: enable

      - role: config_capsman
        radio_mac: 21:34:7D:84:9D:2F
        action: create_enabled
        name_format: cap
        cfg_name: cfg_1
        submenu: caps_provisioning
        action: set

      - role: config_capsman
        numbers_caps_provisioning: 0
        submenu: caps_provisioning
        action: remove
