- name: "change_hostname"
  hosts: router_khv
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_user
        username: testuser
        password: testuser
        privilege: 15
        action: add
