- name: config capsman
  hosts:
  gather_facts: no
  ignore_errors: true
  roles:
      - role: config_bandwidth
        queue_name: stark
        target: 8.8.8.8
        dst: 192.168.81.1
        limit_upload: 2
        limit_download: 2
        pmarks:
        burst_upload: 4
        burst_download: 4
        threshold_upload: 1
        threshold_download: 1
        submenu: simple_queue
        action: add
