- name: "change_hostname"
  hosts: router_khv
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_ip_route
        address: 5.5.5.5/32
        gateway: 1.1.1.1
        action: add
