- name: config mpls
  hosts: SW01.L3.01.LAB
  gather_facts: no
  ignore_errors: true
  roles:
      - role: config_mpls
        interface: ether4
        transport_address: 1.1.1.1
        hold_time: 20s
        hello_interval: 10s
        submenu: ldp_interface
        action: add

      - role: config_mpls
        numbers_ldp_interface: 0
        submenu: ldp_interface
        action: disable

      - role: config_mpls
        numbers_ldp_interface: 0
        submenu: ldp_interface
        action: enable

      - role: config_mpls
        numbers_ldp_interface: 0
        interface: ether4
        transport_address: 8.8.8.8
        dynamic_neighbors: 'no'
        submenu: ldp_interface
        action: set

      - role: config_mpls
        numbers_ldp_interface: 0
        submenu: ldp_interface
        action: remove

      - role: config_mpls
        transport_address: 1.1.1.1
        send_targeted: 'no'
        submenu: ldp_neighbor
        action: add

      - role: config_mpls
        numbers_ldp_neighbor: 0
        submenu: ldp_neighbor
        action: disable

      - role: config_mpls
        numbers_ldp_neighbor: 0
        submenu: ldp_neighbor
        action: enable

      - role: config_mpls
        numbers_ldp_neighbor: 0
        transport_address: 8.8.8.8
        send_targeted: yes
        submenu: ldp_neighbor
        action: set

      - role: config_mpls
        numbers_ldp_neighbor: 0
        submenu: ldp_neighbor
        action: remove

      - role: config_mpls
        range: 16-1048573
        propagate_ttl: 'no'
        submenu: mpls_settings
        action: set

      - role: config_mpls
        ldp: 'yes'
        lsr_id: 1.1.1.1
        transport_address: 8.8.8.8
        loop_detect: 'yes'
        use_explicit_null: 'yes'
        distribute_for_default_route: 'yes'
        submenu: ldp_settings
        action: set
