---
  - name: enable interface ethernet mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable interface ethernet mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: set auto-negotiation interface ethernet mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'


  - name: enable interface ethernet cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_enable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'enable'

  - name: disable interface ethernet cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_disable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'disable'

  - name: set interface ethernet cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_set }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
