---
  - name: enable interface ethernet mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable interface ethernet mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: config auto-negotiation interface ethernet mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'


  - name: config ipaddres interface cisco
    ios_interfaces:
      config: "{{ cisco_config_enable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'enable'

  - name: config ipaddres interface cisco
    ios_interfaces:
      config: "{{ cisco_config_disable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'disable'

  - name: config ipaddres interface cisco
    ios_interfaces:
      config: "{{ cisco_config_set }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
