---

- name: add interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_add }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'add'

- name: remove interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'remove'

- name: enable interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'enable'

- name: disable interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'disable'

- name: set interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_set }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'set'

- name: config ipaddres interface cisco
  raw: "{{ cisco_config }}"
  when: ansible_network_os == 'ios'
