---

- name: add interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_add }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'add'

- name: remove interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'remove'

- name: enable interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'enable'

- name: disable interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'disable'

- name: set interface vlan mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_set }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'set'

# TODO: ios.ios_vlans ?
- name: add interface vlan cisco
  cisco.ios.ios_vlans:
    commands: "{{ cisco_config_add }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'add'

- name: remove interface vlan cisco
  cisco.ios.ios_vlans:
    commands: "{{ mikrotik_config_remove }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'remove'

- name: enable interface vlan cisco
  cisco.ios.ios_vlans:
    commands: "{{ mikrotik_config_enable }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'enable'

- name: disable interface vlan cisco
  cisco.ios.ios_vlans:
    commands: "{{ mikrotik_config_disable }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'disable'

- name: set interface vlan cisco
  cisco.ios.ios_vlans:
    commands: "{{ mikrotik_config_set }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'set'
