---
mikrotik_config_add: /interface vlan add interface={{ interface }} vlan-id={{ vlan_id }} name={{ name_interface_vlan }}
mikrotik_config_remove: /interface vlan remove {{ numbers_inteface_vlan }}
mikrotik_config_enable: /interface vlan enable {{ numbers_inteface_vlan }}
mikrotik_config_disable: /interface vlan disable {{ numbers_inteface_vlan }}

cisco_config: /system identity set name={{ local_hostname }}
