---
mikrotik_config_cap_interface_add: /cap interface add name={{ name }} mtu={{ mtu }} arp={{ arp | default('enabled') }}
mikrotik_config_cap_interface_remove: /cap interface remove numbers={{ numbers_cap_interface }}
mikrotik_config_cap_interface_enable: /cap interface enable numbers={{ numbers_cap_interface }}
mikrotik_config_cap_interface_disable: /cap interface disable numbers={{ numbers_cap_interface }}
mikrotik_config_cap_interface_set: /cap interface set numbers={{ numbers_cap_interface }} mtu={{ mtu }} arp={{ arp | default('enabled') }}

mikrotik_config_caps_provisioning_add: /caps provisioning add radio mac={{ radio_mac }} action={{ action | default('none') }} name format={{ name_format | default('cap') }} master configuration={{ cfg_name }}
mikrotik_config_caps_provisioning_remove: /caps provisioning remove numbers={{ numbers_caps_provisioning }}
mikrotik_config_caps_provisioning_enable: /caps provisioning enable numbers={{ numbers_caps_provisioning }}
mikrotik_config_caps_provisioning_disable: /caps provisioning disable numbers={{ numbers_caps_provisioning }}
mikrotik_config_caps_provisioning_set: /caps provisioning set radio mac={{ radio_mac }} action={{ action | default('none') }} name format={{ name_format | default('cap') }} master configuration={{ cfg_name }}

mikrotik_config_caps_configuration_add: /caps configuration add name={{ cfg_name }} mode={{ mode | default('ap') }} ssid={{ ssid }} hide ssid={{ hide_ssid  | default('no') }} distance={{ distance | default('indoors') }}
mikrotik_config_caps_configuration_remove: /caps configuration remove numbers={{ numbers_caps_configuration }}
mikrotik_config_caps_configuration_set: /caps configuration set name={{ cfg_name }} mode={{ mode | default('ap') }} ssid={{ ssid }} hide ssid={{ hide_ssid  | default('no') }} distance={{ distance | default('indoors') }}

mikrotik_config_caps_channel_add: /caps channel add name={{ channel_name }} frequency={{ frequency }} secondary frequency={{ secondary_frequency }} band={{ band | default('2ghz-b') }} tx power={{ tx_power | default('0') }}
mikrotik_config_caps_channel_remove: /caps channel remove numbers={{ numbers_caps_channel }}
mikrotik_config_caps_channel_set: /caps channel set name={{ channel_name }} frequency={{ frequency }} secondary frequency={{ secondary_frequency }} band={{ band | default('2ghz-b') }} tx power={{ tx_power | default('0') }}

mikrotik_config_caps_datapath_add: /caps datapath add name={{ datapath_name }} mtu={{ mtu }} arp={{ arp | default('disabled') }}  local forwarding={{ local_forwarding }}
mikrotik_config_caps_datapath_remove: /caps datapath remove numbers={{ numbers_caps_configuration }}
mikrotik_config_caps_datapath_set: /caps datapath set name={{ datapath_name }} mtu={{ mtu }} arp={{ arp | default('disabled') }}  local forwarding={{ local_forwarding }}

mikrotik_config_caps_security_cfg_add: /caps security cfg add name={{ security_cfg_name }} authentication type={{ auth_type }} encryption={{ encryption }} group encryption={{ group_encryption }} group key update={{ key_update }} passphrase={{ pass }}
mikrotik_config_caps_security_cfg_remove: /caps security cfg remove numbers={{ numbers_caps_security_cfg }}
mikrotik_config_caps_security_cfg_set: /caps security cfg set name={{ security_cfg_name }} authentication type={{ auth_type }} encryption={{ encryption }} group encryption={{ group_encryption }} group key update={{ key_update }} passphrase={{ pass }}

mikrotik_config_caps_access_rule_add: /cap access rule add mac address={{ mac_address }} mac mask={{ mac_mask }} inerface={{ interface }} ssid regexp={{ ssid regexp }} signal range={{ signal_range }} allow signal out of range={{ time }} action={{ action }}
mikrotik_config_caps_access_rule_remove: /caps access rule remove numbers={{ numbers_caps_access_rule }}
mikrotik_config_caps_access_rule_enable: /caps access rule enable numbers={{ numbers_caps_access_rule }}
mikrotik_config_caps_access_rule_disable: /caps access rule disable numbers={{ numbers_caps_access_rule }}
mikrotik_config_caps_access_rule_set: /cap access rule add mac address={{ mac_address }} mac mask={{ mac_mask }} inerface={{ interface }} ssid regexp={{ ssid regexp }} signal range={{ signal_range }} allow signal out of range={{ time }} action={{ action }}


mikrotik_config_caps_rate_add: /caps rate add name={{ rate_name }} basic rates={{ basic_rates }} supported rates={{ sup_rates }}
mikrotik_config_caps_rate_remove: /caps rate remove numbers={{ numbers_caps_rate }}
mikrotik_config_caps_rate_set: /caps rate set name={{ rate_name }} basic rates={{ basic_rates }} supported rates={{ sup_rates }}
