---
  - name: add bridge mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_add }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'add'

  - name: remove bridge mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'remove'

  - name: enable bridge mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable bridge mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: set bridge mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

# CISCO

  - name: add bridge cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_add }}"
      state: merged
    when:
      - ansible_network_os == 'ios'
      - action == 'add'

  - name: enable bridge cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_enable }}"
      state: replaced
    when:
      - ansible_network_os == 'ios'
      - action == 'enable'

  - name: disable bridge cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_disable }}"
      state: replaced
    when:
      - ansible_network_os == 'ios'
      - action == 'disable'

  - name: remove bridge cisco
    cisco.ios.ios_interfaces:
      config: "{{ cisco_config_remove }}"
      state: deleted
    when:
      - ansible_network_os == 'ios'
      - action == 'remove'
