- name: "change_hostname"
  hosts: router_local
  gather_facts: false
  ignore_errors: true
  roles:
      - role: config_bridge
        name_bridge: TEST
        vlan_filtering: yes
        igmp_snooping: yes
        mtu: 9000
        action: add
      - role: config_bridge
        name_bridge: TEST
        action: disable
      - role: config_bridge
        name_bridge: TEST
        action: enable
      - role: config_bridge
        numbers_route: 1
        name_bridge: TEST_1
        vlan_filtering: yes
        igmp_snooping: yes
        mtu: 9000
        action: set
      - role: config_bridge
        name_bridge: TEST_1
        action: remove
