---
mikrotik_config_add: /ip route add dst-address={{ address }} gateway={{ gateway }} distance={{ distance|default('1', true )}} check-gateway={{ check_gateway | default ('ping', true) }}
mikrotik_config_remove: /ip route remove numbers={{ numbers_route }}
mikrotik_config_enable: /ip route enable numbers={{ numbers_route }}
mikrotik_config_disable: /ip route disable numbers={{ numbers_route }}
mikrotik_config_set: /ip route set numbers={{ numbers_route }} dst-address={{ address }} gateway={{ gateway }} distance={{ distance|default('1', true ) }} check-gateway={{ check_gateway | default ('ping', true) }}
cisco_config: /system identity set name={{ local_hostname }}
