---
mikrotik_config_add: /ip address add interface={{ interface }} address={{ ip_address }} netmask={{ netmask }}
mikrotik_config_remove: /ip address remove {{ numbers_ip_address }}
mikrotik_config_enable: /ip address enable {{ numbers_ip_address }}
mikrotik_config_disable: /ip address disable {{ numbers_ip_address }}
mikrotik_config_set: /ip address set numbers={{ numbers_ip_address }} interface={{ interface }} address={{ ip_address }} netmask={{ netmask }}
cisco_config: /system identity set name={{ local_hostname }}
