---
mikrotik_config:
  - /system ntp client set enabled=yes  primary-ntp={{ ip_ntp }} server-dns-names={{ dns_ntp | default(None) }}
  - system clock set time-zone-autodetect=no time-zone-name={{ time_zone | default(None) }}


# cisco_config: ntp server {{ ntp_servers }}
cisco_config:
  server: "{{ ntp_servers }}"
