---

  - name: change hostname mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config }}"
    when: ansible_network_os == 'routeros'

  - name: change hostname cisco
    raw: "{{ cisco_config }}"
    when: ansible_network_os == 'ios'
