---

- name: add ospf instance mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_instance_add }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'instance'
    - action == 'add'

- name: remove ospf instance mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_instance_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'instance'
    - action == 'remove'

- name: enable ospf instance mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_instance_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'instance'
    - action == 'enable'

- name: disable ospf instance mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_instance_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'instance'
    - action == 'disable'

- name: set ospf instance mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_instance_set }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'instance'
    - action == 'set'

- name: add ospf network mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_network_add }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'network'
    - action == 'add'

- name: remove ospf network mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_network_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'network'
    - action == 'remove'

- name: enable ospf network mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_network_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'network'
    - action == 'enable'

- name: disable ospf network mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_network_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'network'
    - action == 'disable'

- name: set ospf network mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_network_set }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'network'
    - action == 'set'

- name: add ospf area mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_area_add }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'area'
    - action == 'add'

- name: remove ospf area mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_area_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'area'
    - action == 'remove'

- name: enable ospf area mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_area_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'area'
    - action == 'enable'

- name: disable ospf area mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_area_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'area'
    - action == 'disable'

- name: set ospf area mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_ospf_area_set }}"
  when:
    - ansible_network_os == 'routeros'
    - submenu == 'area'
    - action == 'set'


- name: add ospf instance cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_instance_add }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'instance'
    - action == 'add'

- name: remove ospf instance cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_instance_remove }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'instance'
    - action == 'remove'

- name: add ospf network cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_network_add }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'network'
    - action == 'add'

- name: remove ospf network cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_network_remove }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'network'
    - action == 'remove'

- name: add ospf area cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_area_add }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'area'
    - action == 'add'

- name: remove ospf area cisco
  cisco.ios.ios_config: "{{ cisco_config_ospf_area_remove }}"
  when:
    - ansible_network_os == 'ios'
    - submenu == 'area'
    - action == 'remove'
