---
  - name: add user mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_add }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'add'

  - name: remove user mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'remove'

  - name: enable user mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable user mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: set user mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

# CISCO

  - name: add user cisco
    cisco.ios.ios_user: "{{ cisco_config_add }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'add'

  - name: remove user cisco
    cisco.ios.ios_user: "{{ cisco_config_remove }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'remove'

  - name: enable user cisco
    cisco.ios.ios_user: "{{ cisco_config_enable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'enable'

  - name: disable user cisco
    cisco.ios.ios_user: "{{ cisco_config_disable }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'disable'