---
  - name: add user mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_add }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'add'

  - name: remove user mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'remove'

  - name: enable user mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'enable'

  - name: disable user mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'disable'

  - name: set user mikrotik
    routeros_command:
      commands: "{{ mikrotik_config_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

  - name: add user cisco
    ios_user: "{{ cisco_config_add }}"
     state: present
    when:
      - ansible_network_os == 'ios'
      - action == 'add'

  - name: remove user cisco
    ios_user: "{{ cisco_config_remove }}"
     state: absent
    when:
      - ansible_network_os == 'ios'
      - action == 'remove'
