---
mikrotik_config_add: /interface bridge add name={{ bridge }} igmp-snooping={{ igmp_snooping }} vlan-filtering={{ vlan_filtering }}
mikrotik_config_remove: /interface bridge remove {{ bridge }}
mikrotik_config_enable: /interface bridge enable {{ bridge }}
mikrotik_config_disable: /interface bridge disable {{ bridge }}
mikrotik_config_set: /interface bridge set {{ bridge }} igmp-snooping={{ igmp_snooping }} vlan-filtering={{ vlan_filtering }} name={{ rename_bridge }}
cisco_config: /system identity set name={{ local_hostname }}
