---

- name: add dhcp_client mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_add }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'add'

- name: remove dhcp_client mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_remove }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'remove'

- name: enable dhcp_client mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_enable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'enable'

- name: disable dhcp_client mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_disable }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'disable'

- name: set dhcp_client mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config_set }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'set'

# CISCO

- name: add dhcp_client cisco
  cisco.ios.ios_l3_interfaces:
    config: "{{ cisco_config_add }}"
    state: merged
  when:
    - ansible_network_os == 'ios'
    - action == 'add'

- name: remove dhcp_client cisco
  cisco.ios.ios_l3_interfaces:
    config: "{{ cisco_config_remove }}"
    state: deleted
  when:
    - ansible_network_os == 'ios'
    - action == 'remove'

- name: set dhcp_client cisco
  cisco.ios.ios_l3_interfaces:
    config: "{{ cisco_config_set }}"
    state: replaced
  when:
    - ansible_network_os == 'ios'
    - action == 'set'
