---

  - name: add mpls ldp interface mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_interface_add }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_interface'
      - action == 'add'

  - name: remove  mpls ldp interface mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_interface_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_interface'
      - action == 'remove'

  - name: enable mpls ldp interface mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_interface_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_interface'
      - action == 'enable'

  - name: disable mpls ldp interface mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_interface_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_interface'
      - action == 'disable'

  - name: set mpls ldp interface mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_interface_set }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_interface'
      - action == 'set'


  - name: add mpls ldp neighbor mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_neighbor_add }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_neighbor'
      - action == 'add'

  - name: remove  mpls ldp neighbor mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_neighbor_remove }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_neighbor'
      - action == 'remove'

  - name: enable mpls ldp neighbor mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_neighbor_enable }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_neighbor'
      - action == 'enable'

  - name: disable mpls ldp neighbor mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_neighbor_disable }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_neighbor'
      - action == 'disable'

  - name: set mpls ldp neighbor mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_neighbor_set }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_neighbor'
      - action == 'set'

  - name: set mpls settings mikrotik
    community.routeros.command:
       commands: "{{ mikrotik_config_mpls_settings }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'mpls_settings'
      - action == 'set'

  - name: set mpls ldp settings mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config_ldp_settings }}"
    when:
      - ansible_network_os == 'routeros'
      - submenu == 'ldp_settings'
      - action == 'set'

# CISCO

  - name: add dhcp_client cisco
    cisco.ios.ios_l3_interfaces:
      config: "{{ cisco_config_add }}"
      state: merged
    when:
      - ansible_network_os == 'ios'
      - action == 'add'


  - name: remove dhcp_client cisco
    cisco.ios.ios_l3_interfaces:
      config: "{{ cisco_config_remove }}"
      state: deleted
    when:
      - ansible_network_os == 'ios'
      - action == 'remove'
