---
mikrotik_config_add: /ip dhcp-client add interface={{ interface }} add-default-route={{ state_default_route }}
mikrotik_config_remove: /ip dhcp-client remove {{ numbers_dhcp_client }}
mikrotik_config_enable: /ip dhcp-client enable {{ numbers_dhcp_client }}
mikrotik_config_disable: /ip dhcp-client disable {{ numbers_dhcp_client }}
mikrotik_config_set: /ip dhcp-client set numbers={{ numbers_dhcp_client }} interface={{ interface }} add-default-route={{ state_default_route }}
cisco_config: /system identity set name={{ local_hostname }}
