---

  - name: set dns mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_dns_set }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

  - name: set dns cisco
    cisco.ios.ios_config:
      lines: "{{ cisco_dns_set }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
