---

  - name: set dns mikrotik
    community.routeros.command:
      commands: "{{ mikrotik_config }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'

  - name: set dns cisco
    ios_config:
      lines: "{{ cisco_config }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
