---
mikrotik_config_add_simple_queue: /queue simple add name={{  }} target={{  }} dst={{  }} max-limit={{ }}/{{ }} packet-marks={{ | default('no-mark')}} burst-limit={{  }}/{{  }} burst-threshold={{  }}/{{  }}
mikrotik_config_remove_simple_queue: /queue simple remove {{  }}
mikrotik_config_enable_simple_queue: /queue simple enable {{  }}
mikrotik_config_disable_simple_queue: /queue simple disable {{  }}
mikrotik_config_set_simple_queue: /queue simple set {{  }}

mikrotik_config_add_tree_queue: /queue tree add
mikrotik_config_remove_tree_queue: /queue tree remove
mikrotik_config_enable_tree_queue: /queue tree enable
mikrotik_config_disable_tree_queue: /queue tree disable
mikrotik_config_set_tree_queue: /queue tree set

cisco_config_add:
  - name: "{{ interface }}"
    ipv4:
      - address: dhcp

cisco_config_remove:
  - name: "{{ interface }}"
