---

- name: change hostname mikrotik
  community.routeros.command:
    commands: "{{ mikrotik_config }}"
  when:
    - ansible_network_os == 'routeros'
    - action == 'set'

- name: change hostname cisco
  cisco.ios.ios_config:
    lines:
      - "{{ cisco_config }}"
  when:
    - ansible_network_os == 'ios'
    - action == 'set'
