---
  - name: change hostname mikrotik
    routeros_command:
      commands: "{{ mikrotik_config }}"
    when:
      - ansible_network_os == 'routeros'
      - action == 'set'
      
  - name: change hostname cisco
    ios_config:
      lines:
        - "{{ cisco_config }}"
    when:
      - ansible_network_os == 'ios'
      - action == 'set'
